name: Build ISO with Packer

on:
  push:
    branches:
      - main

jobs:
  build-iso:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

    - name: Extract Packer version from file
      id: packer-version
      run: |
        version_string=$(grep "^packer " .tool-versions)
        version=$(echo "$version_string" | awk '{print $2}')
        echo "PACKER_VERSION=$version" >> $GITHUB_STATE

    - name: Install Packer
      uses: hashicorp/setup-packer@ae6b3ed3bec089bbfb576ab7d714df7cbc4b88a4
      with:
        version: ${{ env.PACKER_VERSION }}   

    - name: Install QEMU
      run: sudo apt-get update && sudo apt-get install -y qemu-system-x86

    - name: Initialise Packer
      id: init
      run: packer init packer.pkr.hcl

    - name: Build ISO
      run: packer build packer.pkr.hcl

    - name: Upload ISO to GitHub Packages
      uses: actions/upload-artifact@v2
      with:
        name: my-iso
        path: output/my-iso.iso
