name: Build ISO with Packer

on:
  push:
    branches:
      - main

jobs:
  build-iso:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

    - name: Extract Packer version from file
      id: packer-version
      run: |
        version_string=$(grep "^packer " .tool-versions)
        version=$(echo "$version_string" | awk '{print $2}')
        echo "PACKER_VERSION=$version" >> $GITHUB_STATE

    - name: Install Packer
      uses: hashicorp/setup-packer@ae6b3ed3bec089bbfb576ab7d714df7cbc4b88a4
      with:
        version: ${{ env.PACKER_VERSION }}   

    - name: Set up QEMU
      uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18

    - name: Initialise Packer
      id: init
      run: packer init packer.pkr.hcl

    - name: Build ISO
      run: PACKER_LOG=1 packer build packer.pkr.hcl

    - name: Upload ISO to GitHub Packages
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
      with:
        name: my-iso
        path: output/macbook-ubuntu.zip
